#!/bin/bash
cd
cp -fr .config/i3/ dotfiles/
cp -fr .emacs.d/init.el dotfiles/.emacs.d/
cp -fr .emacs.d/snippets/ dotfiles/.emacs.d/
cd dotfiles/
git add -A
git commit -m "Uppdaterat dotfiles"
git push origin master
